services:
  - type: web
    name: ocr-backend
    env: python
    region: oregon
    buildCommand: |
      sudo apt-get update -y
      sudo apt-get install -y tesseract-ocr tesseract-ocr-spa
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: TESSDATA_PREFIX
        value: /usr/share/tesseract-ocr/4.00/tessdata
      - key: PORT
        value: "10000"
